name: build-deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Analyze with SonarCloud
        run: ./gradlew jacocoTestReport sonar -Dsonar.projectKey=lease-management-service -Dsonar.organization=anant-pawar-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build-docs:
    name: Build Documentation
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: git-checkhot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        id: redoc-build
        shell: bash
        continue-on-error: true
        run: |
          echo "Building Started" &&  npx redoc-cli build .docs/openapi.yaml --title "Lease Management Service API" &&  mv redoc-static.html index.html && echo "Building Finished"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,gradle,.gitignore,.docs,.render,src,README.md,Dockerfile,docker-compose.yaml,gradlew,gradlew.bat,build.gradle,settings.gradle'